"""
dependency_extractor/neo4j_exporter.py
────────────────────────────────────────────────────────────────
Two Neo4j integration modes:

MODE A — APOC XML IMPORT (no driver needed, fully offline)
  Writes graph_dependencies.xml structured for:
    CALL apoc.import.xml("file:///graph_dependencies.xml", {
      relType: "relation",
      label:   "type"
    })

  This mode requires ONLY lxml (no neo4j-python-driver).

MODE B — CYPHER BATCH FILE  (offline Cypher scripts)
  Generates a .cypher file with MERGE statements you can
  run with: cypher-shell < graph.cypher
  No live Neo4j connection needed during generation.

MODE C — LIVE DRIVER  (optional, requires neo4j pip package)
  Connects to a running Neo4j instance and pushes nodes/edges
  in batches via the official Python driver.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import List, Optional

from .models import DependencyGraph, GraphNode, GraphEdge


# ══════════════════════════════════════════════════════════════
#  MODE B: CYPHER BATCH FILE  (primary offline mode)
# ══════════════════════════════════════════════════════════════

def _esc(s: str) -> str:
    """Escape a string for Cypher single-quoted literals."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def _props(node: GraphNode) -> str:
    parts = [
        f"id: '{_esc(node.id)}'",
        f"name: '{_esc(node.name[:120])}'",
        f"language: '{node.language}'",
        f"file_path: '{_esc(node.file_path)}'",
        f"start_line: {node.start_line}",
        f"end_line: {node.end_line}",
        f"is_async: {str(node.is_async).lower()}",
        f"is_exported: {str(node.is_exported).lower()}",
    ]
    if node.docstring:
        parts.append(f"docstring: '{_esc(node.docstring[:300])}'")
    if node.return_type:
        parts.append(f"return_type: '{_esc(node.return_type)}'")
    if node.body_preview:
        parts.append(f"body_preview: '{_esc(node.body_preview[:200])}'")
    return "{" + ", ".join(parts) + "}"


BATCH_SIZE = 500    # nodes / edges per transaction


def export_cypher(graph: DependencyGraph, output_path: str) -> str:
    """
    Generate a Cypher script file that can be run against Neo4j
    without any live connection during generation.

    Run with:
      cypher-shell -u neo4j -p <password> < graph.cypher
    Or via Neo4j Browser: paste and execute.
    """
    lines: List[str] = [
        "// ============================================================",
        f"// Dependency Graph: {graph.name}",
        f"// Nodes: {graph.node_count}   Edges: {graph.edge_count}",
        "// Generated by: Airtel Enterprise AST Engine — Component 3",
        "// Run: cypher-shell < graph.cypher",
        "// ============================================================",
        "",
        "// Create uniqueness constraints (idempotent)",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (n:Node) REQUIRE n.id IS UNIQUE;",
        "",
    ]

    # ── NODES ────────────────────────────────────────────────
    lines.append("// ── NODES ──────────────────────────────────────────")
    nodes = list(graph.nodes.values())
    for i in range(0, len(nodes), BATCH_SIZE):
        chunk = nodes[i:i + BATCH_SIZE]
        lines.append(":begin")
        for node in chunk:
            label = node.node_type.replace(" ", "_")
            props = _props(node)
            lines.append(
                f"MERGE (n:{label} {{id: '{_esc(node.id)}'}}) "
                f"SET n += {props};"
            )
        lines.append(":commit")
        lines.append("")

    # ── EDGES ─────────────────────────────────────────────────
    lines.append("// ── EDGES ──────────────────────────────────────────")
    edges = list(graph.edges)
    for i in range(0, len(edges), BATCH_SIZE):
        chunk = edges[i:i + BATCH_SIZE]
        lines.append(":begin")
        for edge in chunk:
            rel = edge.relation.replace(" ", "_")
            ev  = _esc((edge.evidence or "")[:150])
            lines.append(
                f"MATCH (a {{id: '{_esc(edge.from_id)}'}}), "
                f"(b {{id: '{_esc(edge.to_id)}'}}) "
                f"MERGE (a)-[r:{rel}]->(b) "
                f"SET r.confidence = '{edge.confidence}', "
                f"r.weight = {edge.weight}, "
                f"r.evidence = '{ev}';"
            )
        lines.append(":commit")
        lines.append("")

    cypher = "\n".join(lines)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(cypher, encoding="utf-8")
    kb = Path(output_path).stat().st_size / 1024
    print(f"[neo4j] Cypher script → {output_path}  ({kb:.1f} KB)")
    return output_path


# ══════════════════════════════════════════════════════════════
#  MODE C: LIVE DRIVER  (optional)
# ══════════════════════════════════════════════════════════════

def push_to_neo4j(
    graph:    DependencyGraph,
    uri:      str = "bolt://localhost:7687",
    user:     str = "neo4j",
    password: str = "password",
    database: str = "neo4j",
    batch_size: int = 500,
) -> None:
    """
    Push graph directly to a running Neo4j instance.
    Requires: pip install neo4j

    All operations use MERGE (idempotent — safe to re-run).
    """
    try:
        from neo4j import GraphDatabase
    except ImportError:
        raise RuntimeError(
            "neo4j driver not installed.\n"
            "Run: pip install neo4j\n"
            "Or use export_cypher() for offline Cypher file generation."
        )

    driver = GraphDatabase.driver(uri, auth=(user, password))

    def _push_nodes(tx, chunk: List[GraphNode]):
        for node in chunk:
            label = node.node_type.replace(" ", "_")
            tx.run(
                f"MERGE (n:{label} {{id: $id}}) SET n += $props",
                id=node.id,
                props={
                    "id":          node.id,
                    "name":        node.name[:120],
                    "language":    node.language,
                    "file_path":   node.file_path,
                    "start_line":  node.start_line,
                    "end_line":    node.end_line,
                    "is_async":    node.is_async,
                    "is_exported": node.is_exported,
                    "docstring":   (node.docstring or "")[:300],
                    "body_preview":(node.body_preview or "")[:200],
                },
            )

    def _push_edges(tx, chunk: List[GraphEdge]):
        for edge in chunk:
            rel = edge.relation.replace(" ", "_")
            tx.run(
                f"MATCH (a {{id: $from_id}}), (b {{id: $to_id}}) "
                f"MERGE (a)-[r:{rel}]->(b) "
                f"SET r.confidence = $confidence, "
                f"r.weight = $weight, r.evidence = $evidence",
                from_id=edge.from_id, to_id=edge.to_id,
                confidence=edge.confidence,
                weight=edge.weight,
                evidence=(edge.evidence or "")[:200],
            )

    nodes_list = list(graph.nodes.values())
    edges_list  = list(graph.edges)

    with driver.session(database=database) as session:
        # Constraint
        session.run(
            "CREATE CONSTRAINT IF NOT EXISTS FOR (n:Node) REQUIRE n.id IS UNIQUE"
        )
        # Nodes in batches
        for i in range(0, len(nodes_list), batch_size):
            session.execute_write(_push_nodes, nodes_list[i:i+batch_size])
        # Edges in batches
        for i in range(0, len(edges_list), batch_size):
            session.execute_write(_push_edges, edges_list[i:i+batch_size])

    driver.close()
    print(f"[neo4j] Pushed {graph.node_count} nodes, {graph.edge_count} edges → {uri}")
