"""
knowledge_graph/graph_indexer.py
────────────────────────────────────────────────────────────────
Index and constraint management for Neo4j query performance.

Manages:
  - Lookup indexes (id, name, file_path)
  - Composite indexes (type+file, language+type)
  - Full-text indexes for GraphRAG
  - Relationship property indexes
  - Index usage analysis
  - Index recommendations based on graph shape
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from .models import KnowledgeGraph, KGNodeType
from .graph_schema import KGSchema


# ──────────────────────────────────────────────────────────────
#  RESULT TYPES
# ──────────────────────────────────────────────────────────────

@dataclass
class IndexAnalysis:
    """Analysis of a single index's usage."""
    name:         str
    label:        str
    properties:   List[str]
    index_type:   str     # "BTREE" | "FULLTEXT" | "RANGE"
    state:        str     # "ONLINE" | "POPULATING" | "FAILED"
    usage_count:  int     = 0
    population_percent: float = 0.0


@dataclass
class IndexRecommendation:
    """A recommended index to create."""
    name:        str
    cypher:      str
    reason:      str
    priority:    str    # "high" | "medium" | "low"
    label:       str
    properties:  List[str]


# ══════════════════════════════════════════════════════════════
#  GRAPH INDEXER
# ══════════════════════════════════════════════════════════════

class GraphIndexer:
    """
    Neo4j index management for the knowledge graph.

    Usage (offline — generates Cypher):
        indexer = GraphIndexer()
        cypher = indexer.generate_all_index_cypher()

    Usage (live — with Neo4j driver):
        indexer = GraphIndexer()
        indexer.create_all_indexes(driver)
        analysis = indexer.analyze_index_usage(driver)
    """

    def __init__(self, verbose: bool = True):
        self.verbose = verbose

    # ── Offline Cypher Generation ────────────────────────────

    def generate_all_index_cypher(self) -> str:
        """
        Generate complete index setup Cypher script.
        Can be run offline — no driver needed.
        """
        lines: List[str] = [
            "// ============================================================",
            "// Knowledge Graph Index Setup",
            "// Generated by: Enterprise AI Documentation System — Component 4",
            "// ============================================================",
            "",
            "// ── Uniqueness Constraints ─────────────────────────────────",
        ]
        lines.extend(KGSchema.generate_constraints())
        lines.append("")
        lines.append("// ── Property Indexes ────────────────────────────────────")
        lines.extend(KGSchema.generate_indexes())
        lines.append("")
        lines.append("// ── Full-Text Indexes (GraphRAG) ────────────────────────")
        lines.extend(KGSchema.generate_fulltext_indexes())
        lines.append("")
        lines.append("// ── Relationship Indexes ────────────────────────────────")
        lines.extend(KGSchema.generate_relationship_indexes())

        return "\n".join(lines)

    # ── Live Index Creation ──────────────────────────────────

    def create_all_indexes(
        self,
        driver,
        database: str = "neo4j",
    ) -> List[str]:
        """
        Create all indexes on a live Neo4j instance.

        Returns list of index names created.
        """
        created: List[str] = []
        all_stmts = (
            KGSchema.generate_constraints() +
            KGSchema.generate_indexes() +
            KGSchema.generate_fulltext_indexes() +
            KGSchema.generate_relationship_indexes()
        )

        with driver.session(database=database) as session:
            for stmt in all_stmts:
                try:
                    session.run(stmt.rstrip(";"))
                    # Extract name from statement
                    parts = stmt.split()
                    if len(parts) >= 3:
                        created.append(parts[2])
                except Exception as e:
                    if "already exists" not in str(e).lower():
                        self._log(f"  [warn] {e}")

        self._log(f"[indexer] Created/verified {len(created)} indexes")
        return created

    # ── Full-Text Index (GraphRAG) ───────────────────────────

    def create_fulltext_index(
        self,
        driver,
        database: str = "neo4j",
    ) -> str:
        """
        Create the full-text search index for GraphRAG queries.

        This enables queries like:
          CALL db.index.fulltext.queryNodes('ft_code_search', 'user authentication')
        """
        cypher = (
            "CREATE FULLTEXT INDEX ft_code_search IF NOT EXISTS "
            "FOR (n:CodeEntity) ON EACH [n.name, n.docstring, n.body_preview]"
        )

        with driver.session(database=database) as session:
            try:
                session.run(cypher)
                self._log("[indexer] Full-text index 'ft_code_search' created")
            except Exception as e:
                if "already exists" not in str(e).lower():
                    self._log(f"  [warn] Full-text index: {e}")

        return "ft_code_search"

    # ── Index Analysis ───────────────────────────────────────

    def analyze_index_usage(
        self,
        driver,
        database: str = "neo4j",
    ) -> List[IndexAnalysis]:
        """
        Analyze existing index usage on a live Neo4j instance.
        """
        analyses: List[IndexAnalysis] = []

        with driver.session(database=database) as session:
            result = session.run("SHOW INDEXES")
            for record in result:
                analyses.append(IndexAnalysis(
                    name=record.get("name", ""),
                    label=str(record.get("labelsOrTypes", [])),
                    properties=record.get("properties", []),
                    index_type=record.get("type", "UNKNOWN"),
                    state=record.get("state", "UNKNOWN"),
                    population_percent=record.get("populationPercent", 0.0),
                ))

        self._log(f"[indexer] Analyzed {len(analyses)} indexes")
        return analyses

    # ── Index Recommendations ────────────────────────────────

    def recommend_indexes(
        self,
        kg: KnowledgeGraph,
    ) -> List[IndexRecommendation]:
        """
        Recommend indexes based on graph shape analysis.

        Analyzes:
          - High-degree nodes (need indexed lookups)
          - Common traversal patterns
          - Node type distribution
        """
        recs: List[IndexRecommendation] = []
        stats = kg.stats()
        node_types = stats.get("node_types", {})
        rel_types = stats.get("relation_types", {})

        # Recommend indexes for high-count node types
        for ntype, count in node_types.items():
            if count > 100:
                labels = KGNodeType.neo4j_labels(ntype)
                label = labels[-1] if labels else ntype  # most specific label

                recs.append(IndexRecommendation(
                    name=f"idx_{label.lower()}_name",
                    cypher=(
                        f"CREATE INDEX idx_{label.lower()}_name IF NOT EXISTS "
                        f"FOR (n:{label}) ON (n.name);"
                    ),
                    reason=f"{count} nodes of type {ntype} — name lookup index",
                    priority="high" if count > 1000 else "medium",
                    label=label,
                    properties=["name"],
                ))

        # Recommend relationship indexes for high-count relations
        for rtype, count in rel_types.items():
            if count > 500:
                recs.append(IndexRecommendation(
                    name=f"idx_rel_{rtype.lower()}_conf",
                    cypher=(
                        f"CREATE INDEX idx_rel_{rtype.lower()}_conf IF NOT EXISTS "
                        f"FOR ()-[r:{rtype}]-() ON (r.confidence);"
                    ),
                    reason=f"{count} edges of type {rtype} — confidence filter index",
                    priority="medium",
                    label=rtype,
                    properties=["confidence"],
                ))

        # Always recommend full-text for GraphRAG
        if kg.node_count > 50:
            recs.append(IndexRecommendation(
                name="ft_code_search",
                cypher=(
                    "CREATE FULLTEXT INDEX ft_code_search IF NOT EXISTS "
                    "FOR (n:CodeEntity) ON EACH [n.name, n.docstring, n.body_preview];"
                ),
                reason="Full-text index for GraphRAG semantic search",
                priority="high",
                label="CodeEntity",
                properties=["name", "docstring", "body_preview"],
            ))

        # Service boundary index if clusters exist
        if any(n.service_boundary for n in kg.nodes.values()):
            recs.append(IndexRecommendation(
                name="idx_service_boundary",
                cypher=(
                    "CREATE INDEX idx_service_boundary IF NOT EXISTS "
                    "FOR (n:CodeEntity) ON (n.service_boundary);"
                ),
                reason="Service boundary lookups for microservice queries",
                priority="high",
                label="CodeEntity",
                properties=["service_boundary"],
            ))

        self._log(f"[indexer] {len(recs)} index recommendations")
        return recs

    def _log(self, msg: str):
        if self.verbose:
            print(msg, flush=True)
